# Generated by Django 5.2.4 on 2026-03-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porvoz', '0004_perfil_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='plan_expiration',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual el plan está activo', null=True, verbose_name='Vencimiento del plan'),
        ),
    ]
