# Generated by Django 5.2.4 on 2026-03-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porvoz', '0005_perfil_plan_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='plan',
            field=models.CharField(choices=[('freemium', 'Prueba'), ('growth', 'Growth'), ('multi_business', 'Multi-cuidador')], default='freemium', help_text='Plan de suscripción del usuario', max_length=20, verbose_name='Plan'),
        ),
    ]
