# Generated by Django 5.2.4 on 2026-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porvoz", "0006_alter_perfil_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="plan",
            field=models.CharField(
                choices=[
                    ("freemium", "Básico"),
                    ("growth", "Familiar"),
                    ("multi_business", "Profesional"),
                ],
                default="freemium",
                help_text="Plan de suscripción del usuario",
                max_length=20,
                verbose_name="Plan",
            ),
        ),
    ]
