# Generated by Django 5.2.4 on 2026-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porvoz", "0007_alter_perfil_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="email_llamada_no_atendida",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando una llamada de recordatorio no es atendida",
                verbose_name="Notificar llamadas no atendidas",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="email_toma_aplazada",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando un paciente indica que tomará el medicamento después",
                verbose_name="Notificar cuando paciente aplaza medicamento",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="email_toma_confirmada",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando se confirma que un medicamento fue tomado",
                verbose_name="Notificar cuando medicamento es tomado",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="email_toma_no_confirmada",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando se registra que un medicamento no fue tomado",
                verbose_name="Notificar cuando medicamento NO es tomado",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="email_urgente_minimo",
            field=models.BooleanField(
                default=True,
                help_text="Recibir solo notificaciones de prioridad crítica o urgente",
                verbose_name="Notificar solo alertas críticas/urgentes",
            ),
        ),
    ]
