# Generated by Django 5.2.4 on 2026-04-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porvoz", "0008_perfil_email_llamada_no_atendida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="email_llamada_no_atendida",
            field=models.BooleanField(
                default=False,
                help_text="Recibir email cuando una llamada de recordatorio no es atendida",
                verbose_name="Notificar llamadas no atendidas",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_toma_aplazada",
            field=models.BooleanField(
                default=False,
                help_text="Recibir email cuando un paciente indica que tomará el medicamento después",
                verbose_name="Notificar cuando paciente aplaza medicamento",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_toma_confirmada",
            field=models.BooleanField(
                default=False,
                help_text="Recibir email cuando se confirma que un medicamento fue tomado",
                verbose_name="Notificar cuando medicamento es tomado",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_toma_no_confirmada",
            field=models.BooleanField(
                default=False,
                help_text="Recibir email cuando se registra que un medicamento no fue tomado",
                verbose_name="Notificar cuando medicamento NO es tomado",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_urgente_minimo",
            field=models.BooleanField(
                default=True,
                help_text="Ignorar otras preferencias - solo recibir emails de emergencias reales",
                verbose_name="📌 Solo alertas críticas/urgentes (recomendado)",
            ),
        ),
    ]
