# Generated by Django 5.2.4 on 2026-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porvoz", "0009_alter_perfil_email_llamada_no_atendida_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="email_reintentos_agotados",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando el paciente no responde tras todos los intentos automáticos",
                verbose_name="Notificar cuando se agotan todos los reintentos",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_llamada_no_atendida",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando una llamada de recordatorio no es atendida",
                verbose_name="Notificar llamadas no atendidas",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_toma_aplazada",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando un paciente indica que tomará el medicamento después",
                verbose_name="Notificar cuando paciente aplaza medicamento",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_toma_confirmada",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando se confirma que un medicamento fue tomado",
                verbose_name="Notificar cuando medicamento es tomado",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_toma_no_confirmada",
            field=models.BooleanField(
                default=True,
                help_text="Recibir email cuando se registra que un medicamento no fue tomado",
                verbose_name="Notificar cuando medicamento NO es tomado",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_urgente_minimo",
            field=models.BooleanField(
                default=False,
                help_text="Obsoleto: ya no se muestra en la UI",
                verbose_name="Solo alertas críticas/urgentes",
            ),
        ),
    ]
