# Generated by Django 5.2.11 on 2026-05-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porvoz", "0010_email_prefs_defaults_reintentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="plan_cancelacion_fecha",
            field=models.DateField(
                blank=True,
                help_text="El plan sigue activo hasta esta fecha, luego baja a Básico",
                null=True,
                verbose_name="Fecha de baja por cancelación",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="plan_estado",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("pausado", "Pausado"),
                    ("cancelado", "Cancelado"),
                ],
                default="activo",
                max_length=20,
                verbose_name="Estado del plan",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="plan_pausa_hasta",
            field=models.DateField(
                blank=True,
                help_text="Fecha hasta la cual el plan permanece pausado (se reactiva automáticamente)",
                null=True,
                verbose_name="Plan pausado hasta",
            ),
        ),
    ]
