# Generated by Django 5.2.11 on 2026-05-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("porvoz", "0011_perfil_plan_cancelacion_fecha_perfil_plan_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="plan",
            field=models.CharField(
                choices=[
                    ("freemium", "Gratuito"),
                    ("growth", "Básico"),
                    ("multi_business", "Familiar"),
                    ("profesional", "Profesional"),
                ],
                default="freemium",
                help_text="Plan de suscripción del usuario",
                max_length=20,
                verbose_name="Plan",
            ),
        ),
    ]
