# Generated by Django 5.2.4 on 2026-03-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_rename_porvoz_enfe_paciente_idx_porvoz_enfe_pacient_48fc44_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Mujer'), ('H', 'Hombre'), ('O', 'Otro'), ('', 'Prefiero no decir')], default='', max_length=1, verbose_name='Sexo'),
        ),
    ]
