# Generated by Django 5.2.4 on 2026-03-08 19:11

from django.db import migrations, models


def clear_invalid_sexo(apps, schema_editor):
    """Convierte valores 'O' (Otro) a vacío para compatibilidad."""
    Paciente = apps.get_model("pacientes", "Paciente")
    Paciente.objects.filter(sexo="O").update(sexo="")


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_add_paciente_sexo'),
    ]

    operations = [
        migrations.RunPython(clear_invalid_sexo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1, verbose_name='Sexo'),
        ),
    ]
