# Generated by Django 5.2.4 on 2026-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0006_restrict_sexo_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="parentesco",
            field=models.CharField(
                blank=True,
                help_text="Ej: Padre, Madre, Hijo/a, Cónyuge, etc.",
                max_length=50,
                verbose_name="Parentesco / Relación",
            ),
        ),
    ]
