# Generated by Django 5.2.4 on 2026-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0008_add_horarios_ia_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="America/Bogota",
                help_text="Ej: America/Bogota, America/Mexico_City. Para programar llamadas en hora local.",
                max_length=50,
                verbose_name="Zona horaria",
            ),
        ),
    ]
