# Generated by Django 5.2.11 on 2026-05-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0009_alter_paciente_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="alergias",
            field=models.TextField(
                blank=True,
                help_text="Medicamentos, alimentos u otras alergias",
                verbose_name="Alergias conocidas",
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="eps",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="EPS / Aseguradora"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="medico_tratante",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Médico tratante"
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="tipo_sangre",
            field=models.CharField(
                blank=True,
                help_text="Ej: O+, A-, B+, AB+",
                max_length=5,
                verbose_name="Tipo de sangre",
            ),
        ),
    ]
