# Generated by Django 5.2.11 on 2026-05-08 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("freemium", "Básico"),
                            ("growth", "Familiar"),
                            ("multi_business", "Profesional"),
                        ],
                        help_text="Plan que otorga este código",
                        max_length=20,
                    ),
                ),
                (
                    "duracion_meses",
                    models.IntegerField(
                        choices=[
                            (1, "1 mes"),
                            (3, "3 meses"),
                            (6, "6 meses"),
                            (12, "1 año"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("usado", "Usado"),
                            ("expirado", "Expirado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("usado_en", models.DateTimeField(blank=True, null=True)),
                ("expira_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codigos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_usado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codigos_usados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="PagoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("freemium", "Básico"),
                            ("growth", "Familiar"),
                            ("multi_business", "Profesional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duracion_meses", models.IntegerField()),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("codigo", "Código de acceso"),
                            ("transferencia", "Transferencia bancaria"),
                            ("gratuito", "Acceso gratuito"),
                            ("promocion", "Promoción"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto en COP",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "referencia_pago",
                    models.CharField(
                        blank=True,
                        help_text="Ej: número de comprobante de transferencia",
                        max_length=100,
                    ),
                ),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("fecha_hasta", models.DateField()),
                ("notas", models.TextField(blank=True)),
                (
                    "codigo_usado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_panel.codigoacceso",
                    ),
                ),
                (
                    "procesado_por",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_procesados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_historico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="TicketSoporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_progreso", "En progreso"),
                            ("resuelto", "Resuelto"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="abierto",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("resuelto_en", models.DateTimeField(blank=True, null=True)),
                ("respuesta", models.TextField(blank=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="codigoacceso",
            index=models.Index(fields=["codigo"], name="admin_panel_codigo_61d597_idx"),
        ),
        migrations.AddIndex(
            model_name="codigoacceso",
            index=models.Index(fields=["estado"], name="admin_panel_estado_3b81a7_idx"),
        ),
    ]
