# Generated by Django 5.2.11 on 2026-05-08 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketsoporte",
            name="respuesta",
        ),
        migrations.AddField(
            model_name="ticketsoporte",
            name="email_contacto",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="ticketsoporte",
            name="nombre_contacto",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="ticketsoporte",
            name="telefono_contacto",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="ticketsoporte",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MensajeTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_admin", models.BooleanField(default=False)),
                ("contenido", models.TextField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensajes_soporte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="admin_panel.ticketsoporte",
                    ),
                ),
            ],
            options={
                "ordering": ["creado_en"],
            },
        ),
    ]
