# Generated by Django 5.2.11 on 2026-05-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_remove_ticketsoporte_respuesta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagohistorico",
            name="comprobante",
            field=models.FileField(
                blank=True, null=True, upload_to="comprobantes_pago/"
            ),
        ),
        migrations.AlterField(
            model_name="codigoacceso",
            name="plan",
            field=models.CharField(
                choices=[
                    ("freemium", "Gratuito"),
                    ("growth", "Básico"),
                    ("multi_business", "Familiar"),
                    ("profesional", "Profesional"),
                ],
                help_text="Plan que otorga este código",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pagohistorico",
            name="plan",
            field=models.CharField(
                choices=[
                    ("freemium", "Gratuito"),
                    ("growth", "Básico"),
                    ("multi_business", "Familiar"),
                    ("profesional", "Profesional"),
                ],
                max_length=20,
            ),
        ),
    ]
