# Generated by Django 5.2.11 on 2026-05-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_panel",
            "0003_pagohistorico_comprobante_alter_codigoacceso_plan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="codigoacceso",
            name="fecha_limite_canje",
            field=models.DateField(
                blank=True,
                help_text="Fecha límite para canjear este código. El plan empieza al canjearlo.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pagohistorico",
            name="costo_estimado",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Costo Twilio + infra estimado en COP",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pagohistorico",
            name="ganancia_neta",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="monto − costo_estimado",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pagohistorico",
            name="metodo_transferencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bancolombia", "Bancolombia"),
                    ("nequi", "Nequi"),
                    ("efectivo", "Efectivo"),
                    ("otro", "Otro"),
                ],
                max_length=20,
            ),
        ),
    ]
