# Generated by Django 5.2.11 on 2026-05-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_codigoacceso_fecha_limite_canje_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("freemium", "Gratuito"),
                            ("growth", "Básico"),
                            ("multi_business", "Familiar"),
                            ("profesional", "Profesional"),
                        ],
                        db_index=True,
                        help_text="Clave del plan (freemium, growth, multi_business, profesional)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del plan (Gratuito, Básico, Familiar, Profesional)",
                        max_length=100,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, help_text="Descripción breve del plan"
                    ),
                ),
                (
                    "precio_mensual",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Precio mensual en COP que cobra el usuario",
                        max_digits=10,
                    ),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Costo estimado mensual (Twilio + infraestructura)",
                        max_digits=10,
                    ),
                ),
                (
                    "limite_pacientes",
                    models.IntegerField(
                        default=1, help_text="Cantidad máxima de pacientes"
                    ),
                ),
                (
                    "limite_medicamentos",
                    models.IntegerField(
                        blank=True,
                        help_text="Máximo medicamentos por paciente (null = ilimitado)",
                        null=True,
                    ),
                ),
                (
                    "limite_llamadas_mes",
                    models.IntegerField(
                        default=15, help_text="Máximo de llamadas automatizadas por mes"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si es False, este plan no aparece en el login",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Plan",
                "verbose_name_plural": "Configuraciones de Planes",
                "ordering": ["precio_mensual"],
            },
        ),
    ]
