# Generated by Django 5.2.12 on 2026-03-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='initiated')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='contacts.contact')),
                ('reminder', models.ForeignKey(blank=True, db_column='reminder_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='reminders.reminder')),
            ],
            options={
                'db_table': 'call_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
