# Generated by Django 5.2.4 on 2026-04-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("llamadas", "0003_remove_notificacion_to_notificaciones_app"),
        ("medicamentos", "0005_add_horarios_ia_fields"),
        ("pacientes", "0008_add_horarios_ia_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Llamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("en_curso", "En curso"),
                            ("completada", "Completada"),
                            ("fallida", "Fallida"),
                        ],
                        default="programada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(verbose_name="Fecha programada"),
                ),
                (
                    "fecha_ejecutada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha ejecutada"
                    ),
                ),
                (
                    "call_sid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="ID de llamada (Twilio)",
                    ),
                ),
                (
                    "duracion",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duración (segundos)"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llamadas",
                        to="medicamentos.medicamento",
                        verbose_name="Medicamento",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llamadas",
                        to="pacientes.paciente",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llamadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Llamada",
                "verbose_name_plural": "Llamadas",
                "db_table": "porvoz_llamada",
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaLlamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "como_respondio",
                    models.CharField(
                        choices=[
                            ("atendida", "Atendida"),
                            ("no_atendida", "No atendida"),
                            ("buzon", "Buzón de voz"),
                        ],
                        max_length=20,
                        verbose_name="Cómo respondió",
                    ),
                ),
                (
                    "transcripcion",
                    models.TextField(blank=True, verbose_name="Transcripción"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "llamada",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuesta",
                        to="llamadas.llamada",
                        verbose_name="Llamada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de llamada",
                "verbose_name_plural": "Respuestas de llamadas",
                "db_table": "porvoz_respuesta_llamada",
            },
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(
                fields=["usuario", "estado"], name="porvoz_llam_usuario_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(fields=["paciente"], name="porvoz_llam_paciente_idx"),
        ),
        migrations.AddIndex(
            model_name="llamada",
            index=models.Index(
                fields=["fecha_programada"], name="porvoz_llam_fecha_idx"
            ),
        ),
    ]
