# Generated by Django 5.2.4 on 2026-04-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llamadas", "0004_add_llamada_respuesta"),
    ]

    operations = [
        migrations.AddField(
            model_name="respuestallamada",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("confirmada", "Confirmó toma"),
                    ("negativa", "No tomó"),
                    ("sin_confirmar", "Sin confirmar"),
                ],
                default="sin_confirmar",
                max_length=20,
                verbose_name="Resultado de toma",
            ),
        ),
    ]
