# Generated by Django 5.2.4 on 2026-04-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llamadas", "0005_add_resultado_to_respuesta_llamada"),
    ]

    operations = [
        migrations.AddField(
            model_name="llamada",
            name="intentos",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Número de intento"
            ),
        ),
    ]
