# Generated by Django 5.2.4 on 2026-04-07 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("llamadas", "0006_add_intentos_y_reintentos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="respuestallamada",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("confirmada", "Confirmó toma"),
                    ("negativa", "No tomó"),
                    ("despues", "Lo tomará después"),
                    ("sin_confirmar", "Sin confirmar"),
                ],
                default="sin_confirmar",
                max_length=20,
                verbose_name="Resultado de toma",
            ),
        ),
        migrations.CreateModel(
            name="AuditoriaLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objeto_id",
                    models.PositiveIntegerField(help_text="ID del objeto afectado"),
                ),
                (
                    "objeto_str",
                    models.CharField(
                        blank=True,
                        help_text="Nombre/descripción del objeto para legibilidad",
                        max_length=255,
                        verbose_name="Representación del objeto",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("create", "Crear"),
                            ("update", "Actualizar"),
                            ("delete", "Eliminar"),
                        ],
                        max_length=10,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "cambios",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Para UPDATE: {campo: [valor_anterior, valor_nuevo]}",
                        verbose_name="Cambios",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "contenido_type",
                    models.ForeignKey(
                        help_text="Modelo afectado (Medicamento, Paciente, etc)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoría",
                "verbose_name_plural": "Auditorías",
                "db_table": "porvoz_auditoria",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "timestamp"],
                        name="porvoz_audi_usuario_7fd82e_idx",
                    ),
                    models.Index(
                        fields=["contenido_type", "objeto_id"],
                        name="porvoz_audi_conteni_f884f8_idx",
                    ),
                    models.Index(
                        fields=["accion"], name="porvoz_audi_accion_ad253b_idx"
                    ),
                ],
            },
        ),
    ]
