# Generated by Django 5.2.4 on 2026-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llamadas", "0007_alter_respuestallamada_resultado_auditorialog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respuestallamada",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("confirmada", "Confirmó toma"),
                    ("negativa", "No tomó"),
                    ("despues", "Lo tomará después"),
                    ("sin_confirmar", "Sin confirmar"),
                    ("rechazo_tratamiento", "Rechaza tratamiento"),
                    ("emergencia", "Posible emergencia"),
                ],
                default="sin_confirmar",
                max_length=20,
                verbose_name="Resultado de toma",
            ),
        ),
    ]
