# Generated by Django 5.2.4 on 2026-03-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0002_remove_call_fields_from_notificacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("recordatorio", "Recordatorio"),
                    ("alerta", "Alerta"),
                    ("sistema", "Sistema"),
                    ("llamada", "Llamada"),
                ],
                default="sistema",
                max_length=20,
                verbose_name="Tipo de notificación",
            ),
        ),
    ]
