# Generated by Django 5.2.4 on 2026-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificaciones", "0003_alter_notificacion_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacion",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("baja", "Baja"),
                    ("normal", "Normal"),
                    ("urgente", "Urgente"),
                    ("critica", "Crítica"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Prioridad",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="url_detalle",
            field=models.URLField(
                blank=True,
                help_text="Enlace al evento relacionado",
                null=True,
                verbose_name="URL detalle",
            ),
        ),
    ]
