# Generated by Django 5.2.11 on 2026-02-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_medicamento_frecuencia'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicamento',
            new_name='porvoz_medi_pacient_79ec81_idx',
            old_name='porvoz_medi_paciente_idx',
        ),
        migrations.RenameIndex(
            model_name='medicamento',
            new_name='porvoz_medi_horario_f2da37_idx',
            old_name='porvoz_medi_horario_idx',
        ),
    ]
