# Generated by Django 5.2.4 on 2026-03-09 02:16

import django.db.models.deletion
from django.db import migrations, models


def migrar_horarios_legacy(apps, schema_editor):
    """Copia horario existente a HorarioMedicamento para medicamentos con frecuencia horario."""
    Medicamento = apps.get_model("medicamentos", "Medicamento")
    HorarioMedicamento = apps.get_model("medicamentos", "HorarioMedicamento")
    for med in Medicamento.objects.filter(frecuencia_tipo="horario", horario__isnull=False):
        HorarioMedicamento.objects.create(medicamento=med, hora=med.horario, orden=0)


def reverse_migrar_horarios(apps, schema_editor):
    """Revierte: copia primer horario de vuelta a horario (por si se necesita rollback)."""
    Medicamento = apps.get_model("medicamentos", "Medicamento")
    HorarioMedicamento = apps.get_model("medicamentos", "HorarioMedicamento")
    for med in Medicamento.objects.filter(frecuencia_tipo="horario"):
        first = HorarioMedicamento.objects.filter(medicamento=med).order_by("orden", "hora").first()
        if first:
            med.horario = first.hora
            med.save(update_fields=["horario"])


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0004_medicamento_duracion_dias"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamento",
            name="fecha_inicio_tratamiento",
            field=models.DateField(
                blank=True,
                help_text="Para 'Cada X horas': fecha desde la que se calculan las tomas",
                null=True,
                verbose_name="Fecha de inicio del tratamiento",
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="instrucciones_llamada",
            field=models.TextField(
                blank=True,
                help_text="Contexto para la IA: 'Recordar con el desayuno', 'Preguntar efectos secundarios', etc.",
                verbose_name="Instrucciones para la llamada",
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="minutos_antes_llamada",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Llamar X minutos antes de la hora de toma (ej: 15)",
                verbose_name="Minutos antes para llamar",
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="horario",
            field=models.TimeField(
                blank=True,
                help_text="Mantenido para compatibilidad; usar horarios cuando existan",
                null=True,
                verbose_name="Horario de toma (legacy)",
            ),
        ),
        migrations.CreateModel(
            name="HorarioMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hora", models.TimeField(verbose_name="Hora de toma")),
                ("orden", models.PositiveSmallIntegerField(default=0, verbose_name="Orden")),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="medicamentos.medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de medicamento",
                "verbose_name_plural": "Horarios de medicamento",
                "db_table": "porvoz_horario_medicamento",
                "ordering": ["orden", "hora"],
            },
        ),
        migrations.RunPython(migrar_horarios_legacy, reverse_migrar_horarios),
    ]
