# Generated by Django 5.2.4 on 2026-04-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0005_add_horarios_ia_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicamento",
            name="duracion_dias",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Dejar vacío para tratamiento indefinido; o indicar días (ej: 7, 30).",
                null=True,
                verbose_name="Duración en días",
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="instrucciones_llamada",
            field=models.CharField(
                blank=True,
                help_text="Máx 200 caracteres. No incluir datos médicos sensibles.",
                max_length=200,
                verbose_name="Instrucciones para la llamada",
            ),
        ),
    ]
