# Generated by Django 5.2.4 on 2026-04-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0006_instrucciones_llamada_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamento",
            name="max_reintentos",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Intentos adicionales si no responde o dice que no tomó (0 = sin reintento, máx 3).",
                verbose_name="Reintentos automáticos",
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="minutos_entre_reintentos",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Minutos de espera antes de reintentar la llamada.",
                verbose_name="Minutos entre reintentos",
            ),
        ),
    ]
