# Generated by Django 5.2.11 on 2026-05-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamentos", "0007_add_intentos_y_reintentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamento",
            name="pausado",
            field=models.BooleanField(
                default=False, verbose_name="Pausado temporalmente"
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="pausado_hasta",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que se reactiva automáticamente",
                null=True,
                verbose_name="Pausado hasta",
            ),
        ),
    ]
